server:
  port: 8085
spring:
  cloud:
    config:
      server:
        git:
          default-label: circuit-breaker
          uri: https://github.com/Miguel-RJ/microservicios-tutorial
          search-paths: config-data
  application:
    name: config-service